from __future__ import annotations

from ariadne.ibom_parser import parse_ibom_bom

# A small LZ-String base64-compressed `pcbdata` payload generated by the
# reference lz-string algorithm. Decompresses to:
# {"metadata": {...}, "bom": {
#   "fields": {"0": ["10K", "Resistor_SMD:R_0603"],
#              "1": ["100nF", "Capacitor_SMD:C_0805"],
#              "2": ["DNP_VALUE", "DNP_FOOT"]},
#   "both": [[["R1", 0], ["R2", 0]], [["C1", 1]]],
#   "F": [[["C2", 1]]], "B": [], "skipped": [2]}}
PAYLOAD = (
    "N4IgtgpgLghgJjWIBcACUUCWUA2EWogAqEAzlCADSEBOEAbpqZgPYB2BIVhCU+aIAEwAG"
    "QQDYAtMICMU6SAC+1EACMWYAqABmmCDjilNIYQQDaIacIDS3EACUyTKCxoB9AMoBZACLI"
    "7r4TFhAGYQAF1leTRzS2E2ADFbAGEYAAcYAGNsFw8fZCSAgA5hAFZw5UEzEG8AOQAFVw"
    "A1AEEAGQBVAFFbWob4gHl+onClQjUoAAszU3M7eWphCNRZyoWwpZmQJPnUaXWlkEToza"
    "TV3f3lACEzA9IAa0xU1Ig4M0Ew0ZBMNTBXeggaMx2Jx6IIAHQATjBJgUQA"
)

# Variant where `both` is empty so the front/back layer (`F`) is used.
# Decompresses to a bom with fields {"0": ["10K", "R_0603"]}, both: [],
# F: [[["R1", 0], ["R2", 0]]], B: [], skipped: [].
PAYLOAD_C = (
    "N4IgtgpgLghgJjWIBcACUUCWUA2EWogAqEAzlCAL4A0hARgPZgGgBmmEOcpLIADAQDaIA"
    "Ix8A0iFogASmUzkGAJwD6AZQCyAEWQyVfAGx8AzCAC6NegygALIWekAxIYOEyRU1Hweo3"
    "AJk9vMx8QACF7aVIAa0wAB1iIOHtLEExGMBUANwglUkwGADsCEEy/ADoATjKBSiA=="
)


def _ibom_file(tmp_path, payload=PAYLOAD, var=True):
    p = tmp_path / "board_ibom.html"
    body = (
        '<html><head></head><body>'
        '<script type="text/javascript">'
        "var pcbdata = JSON.parse(LZString.decompressFromBase64("
        f'"{payload}"));'
        "</script>"
        "</body></html>"
        if var else
        "<html><body>nothing</body></html>"
    )
    p.write_text(body, encoding="utf-8")
    return str(p)


def test_parse_groups_and_quantity(tmp_path):
    entries = parse_ibom_bom(_ibom_file(tmp_path))
    assert len(entries) == 2
    r = entries[0]
    assert r.reference_designator == "R1,R2"
    assert r.quantity == 2
    assert r.part_value == "10K"
    assert r.package == "Resistor_SMD:R_0603"
    assert r.mounting_type == "SMT"
    assert r.item_number == 1


def test_parse_prefers_both_over_layers(tmp_path):
    # `both` always takes precedence; F/B do not duplicate its rows.
    entries = parse_ibom_bom(_ibom_file(tmp_path))
    refs = {e.reference_designator for e in entries}
    assert refs == {"R1,R2", "C1"}
    assert "C2" not in refs


def test_parse_falls_back_to_layers_when_both_empty(tmp_path):
    entries = parse_ibom_bom(_ibom_file(tmp_path, payload=PAYLOAD_C))
    assert len(entries) == 1
    assert entries[0].reference_designator == "R1,R2"
    assert entries[0].quantity == 2


def test_parse_skips_dnp(tmp_path):
    entries = parse_ibom_bom(_ibom_file(tmp_path))
    for e in entries:
        assert e.part_value != "DNP_VALUE"


def test_parse_missing_payload_raises(tmp_path):
    import pytest
    with pytest.raises(ValueError):
        parse_ibom_bom(_ibom_file(tmp_path, payload="!!!!notbase64!!!!"))


def test_parse_non_ibom_raises(tmp_path):
    import pytest
    with pytest.raises(ValueError):
        parse_ibom_bom(_ibom_file(tmp_path, var=False))
